-- File: loader/Default-config-gag2.lua
_G.GAGConfig = _G.GAGConfig or {
    ["Harvest"] = {
        ["Auto Harvest"]  = true,
        ["Sell At"]       = 85,
        ["Sell Every"]    = 40,
        ["Only Harvest"]  = {},
        ["Don't Harvest"] = {},
        ["Wait For Mutation"] = {"Bamboo", "Mushroom"},
        ["Auto Unfavorite"] = false,
    },
    ["Planting"] = {
        ["Auto Plant"]  = true,
        ["Plant Plan"]  = {},
        ["Only Plant"]  = {},
        ["Minimum Seed"] = "Bamboo",
        ["Layout"]      = "compact",
        ["Don't Plant"] = {},
        ["Don't Buy"]   = {},
        ["Keep Seeds"]  = {},
        ["Plant Limit"] = 0,
        ["Never Shovel"] = {},
        ["Shovel Up To"] = "",
        ["Shovel Mutated"] = false,
        ["Buy Seeds"]   = {},
    },
    ["Money"] = {
        ["Keep Cash"]          = 15000,
        ["Auto Expand Plot"]   = true,
        ["Max Expansions"]     = 5,
        ["Expand If Over"]     = 1500000,
        ["Auto Replace Plants"] = true,
    },
    ["Never Sell"] = {
        ["By Mutation"] = {},
        ["By Fruit"]    = {},
        ["Exact"]       = {},
    },
    ["Pets"] = {
        ["Buy"] = {
            "Unicorn",
            ["Deer"] = 6,
            ["Raccoon"] = { Mega = 1, Rainbow = 1 },
            ["Bear"]    = { Mega = 2 },
        },
        ["Equip"]          = { Unicorn = 6 },
        ["Auto Buy Slots"] = true,
        ["Max Pet Slots"]  = 6,
    },
    ["Gear"] = {
        ["Auto Buy"]             = true,
        ["Keep Cash"]            = 15000,
        ["Sprinkler Coverage"]   = "concentrate",
        ["Place Sprinklers"]     = { ["best"] = 4 },
        ["Best Sprinkler Up To"] = "Rare Sprinkler",
        ["Keep Gear"]            = {},
        ["Buy Gear"]             = { "Super Sprinkler"},
    },
    ["Event Seeds"] = {
        ["Auto Claim"] = true,
    },
    ["Mail"] = {
        ["Auto Claim"] = true,
        ["Auto Accept Gift"] = true,
        ["Send To"]    = "",
        ["Send Every"] = 0,
        ["Send"]       = {
            "Moon Bloom", "Dragon's Breath", "Gold", "Rainbow",
            "Deer", "GoldenDragonfly", "Unicorn", "Robin", "Raccoon", "Turtle",
            "Super Sprinkler", "Legendary Sprinkler", "Super Watering Can",
        },
    },
    ["Misc"] = {
        ["Auto Return To Garden"] = true,
        ["Show Stats"]            = true,
        ["Hide Game UI"]          = false,
        ["Show Console"]          = false,
        ["Smart Travel"]          = true,
        ["Auto Daily Deal"]       = true,
        ["Walk Speed"]            = 0,
        ["Slide Speed"]           = 30,
        ["Fast Travel"]           = false,
        ["Teleport"]              = true,
    },
    ["Friends"] = {
        ["Auto Accept"] = false,
        ["Auto Send"]   = false,
    },
    ["Auction"] = {
        ["Auto Buy"]   = true,
        ["Buy"]        = {
            ["Uncommon Seed Pack"] = 50000,
            ["Mushroom"] = 2000000,
            ["Bamboo"] = 30000,
        },
        ["Keep Cash"]  = 0,
        ["Check Every"] = 0.2,
        ["Max Tries"]  = 10,
    },
    ["Eggs"] = {
        ["Auto Open"] = false,
        ["Open"]      = {
            "Common Egg", "Uncommon Egg",
        },
    },
    ["Performance"] = {
        ["FPS Cap"]              = 0,
        ["Low Graphics"]         = true,
        ["Remove Other Gardens"] = true,
        ["Hide Crop Visuals"]    = true,
        ["Hide Fruit Visuals"]   = false,
        ["Hide Players"]         = true,
    },
    ["Debug"] = {
        ["Log To File"] = true,
        ["Console"]     = true,
    },
}
